services:
  local-writer-backend:
    build:
      context: writer-backend/
      dockerfile: Dockerfile
    ports:
      - "${LOCAL_PORT:-3000}:3000"
    container_name: local-backend
    environment:
      - JWT_SECRET=${JWT_SECRET:-secret}
      - MONGODB_URI=${LOCAL_MONGODB_URI:-mongodb://admin:admin@local-database:27017/writer?authSource=admin}
    depends_on:
      - local-database
    restart: unless-stopped

  local-database:
    image: mongodb/mongodb-community-server:latest
    container_name: local-database
    volumes:
      - ${LOCAL_VOLUME:-./mongo-data}/data:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-admin}
    user: "1000:1000"
    restart: unless-stopped
