services:
  writer-frontend:
    image: adityajyoti/writer-frontend:latest
    container_name: frontend
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - JWT_SECRET=${JWT_SECRET:-secret}
      - PUBLIC_API_BASE=${PUBLIC_API_BASE:-http://writer-backend:3000}
    depends_on:
      - writer-backend
    restart: unless-stopped

  writer-backend:
    image: adityajyoti/writer-backend:latest
    container_name: backend
    environment:
      - JWT_SECRET=${JWT_SECRET:-secret}
      - MONGODB_URI=${MONGO_URI:-mongodb://admin:admin@database:27017/writer?authSource=admin}
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: mongodb/mongodb-community-server:latest
    container_name: database
    volumes:
      - ${VOLUME:-./mongo-data}/data:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-admin}
    user: "1000:1000"
    restart: unless-stopped
