services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "${PORT:-3000}:3000"
    env_file: .env

  database:
    image: mongodb/mongodb-community-server:latest
    container_name: database
    volumes:
      - ${VOLUME}/data:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${PASSWORD}
    user: "1000:1000"
