name: Build and conditionally push writer backend docker image to docker Hub

on:
  push:
    branches:
      - main
    paths:
      - "writer-backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # CPU emulator to facilitate building for ARM64 and AMD64
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # Sets up Docker Buildx, a Docker CLI plugin for extended build capabilities with BuildKit
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Caches the docker build layers to speed up the build process
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-writer-backend-${{ github.sha }}
          restore-keys: ${{ runner.os }}-writer-backend-
      # Build the Docker image
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./writer-backend
          file: ./writer-backend/Dockerfile
          tags: ${{ vars.DOCKER_USERNAME }}/writer-backend:latest
          platforms: linux/amd64,linux/arm64
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  approve:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Push the Docker image
      - name: Push image
        uses: docker/build-push-action@v3
        with:
          context: ./writer-backend
          file: ./writer-backend/Dockerfile
          tags: ${{ vars.DOCKER_USERNAME }}/writer-backend:latest
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
