name: Build and Conditionally Push Writer Backend Docker Image to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - "writer-backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-writer-backend-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-writer-backend-

      - name: Build image (without pushing)
        uses: docker/build-push-action@v3
        with:
          context: writer-backend
          file: writer-backend/Dockerfile
          tags: ${{ vars.DOCKERHUB_USERNAME }}/writer-backend:build-preview
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  approve-and-retag:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Pull preview image
        run: |
          docker pull ${{ vars.DOCKERHUB_USERNAME }}/writer-backend:build-preview

      - name: Retag as latest
        run: |
          docker tag ${{ vars.DOCKERHUB_USERNAME }}/writer-backend:build-preview ${{ vars.DOCKERHUB_USERNAME }}/writer-backend:latest

      - name: Push latest tag
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/writer-backend:latest

