name: Cleanup Unapproved Preview Images

on:
  schedule:
    - cron: "0 * * * *" # every hour

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check if preview image exists
        run: |
          docker manifest inspect ${{ secrets.DOCKERHUB_USERNAME }}/writer-backend:build-preview || exit 0

          echo "Deleting preview image..."
          curl -X DELETE \
            -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" \
            "https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/writer-backend/tags/build-preview/"
